### ISSUE TITLE
Найти или нарисовать новый тайлсет для карт

### ISSUE THREAD

**Issue by Fedor-Lyanguzov** [PFML239/LazyBomberman#3]
Текущий тайлсет слабо подходит для отрисовки карт, так как вообще говоря не включает в себя "стен" и пр.

**Comment by HDDCableHD** [comment]
Готов сделать

**Comment by HDDCableHD** [comment]
Примерно такой должен быть tileset? 
http://www.spriters-resource.com/snes/sbomber/
